[package]
org = "ballerinax"
name = "gcloud.pubsub"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["pubsub", "google cloud", "messaging", "cloud", "gcp"]
repository = "https://github.com/ballerina-platform/module-ballerinax-gcloud.pubsub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[build-options]
observabilityIncluded=true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "gcloud.pubsub-native"
version = "@toml.version@"
path = "../native/build/libs/gcloud.pubsub-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.cloud"
artifactId = "google-cloud-pubsub"
version = "@gcloud.pubsub.version@"
path = "./lib/google-cloud-pubsub-@gcloud.pubsub.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "gax"
version = "@gax.version@"
path = "./lib/gax-@gax.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "gax-grpc"
version = "@gax.version@"
path = "./lib/gax-grpc-@gax.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-credentials"
version = "@google.auth.version@"
path = "./lib/google-auth-library-credentials-@google.auth.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-oauth2-http"
version = "@google.auth.version@"
path = "./lib/google-auth-library-oauth2-http-@google.auth.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-netty-shaded"
version = "@grpc.version@"
path = "./lib/grpc-netty-shaded-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-api"
version = "@grpc.version@"
path = "./lib/grpc-api-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-core"
version = "@grpc.version@"
path = "./lib/grpc-core-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-auth"
version = "@grpc.version@"
path = "./lib/grpc-auth-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-stub"
version = "@grpc.version@"
path = "./lib/grpc-stub-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-protobuf"
version = "@grpc.version@"
path = "./lib/grpc-protobuf-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-protobuf-lite"
version = "@grpc.version@"
path = "./lib/grpc-protobuf-lite-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-context"
version = "@grpc.version@"
path = "./lib/grpc-context-@grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-cloud-pubsub-v1"
version = "@google.grpc.version@"
path = "./lib/proto-google-cloud-pubsub-v1-@google.grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "grpc-google-cloud-pubsub-v1"
version = "@google.grpc.version@"
path = "./lib/grpc-google-cloud-pubsub-v1-@google.grpc.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "@google.proto.commons.version@"
path = "./lib/proto-google-common-protos-@google.proto.commons.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-iam-v1"
version = "@google.proto.iam.version@"
path = "./lib/proto-google-iam-v1-@google.proto.iam.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "@protobuf.version@"
path = "./lib/protobuf-java-@protobuf.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "api-common"
version = "@google.api.common.version@"
path = "./lib/api-common-@google.api.common.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client"
version = "@google.http.client.version@"
path = "./lib/google-http-client-@google.http.client.version@.jar"

[[platform.java21.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-api"
version = "@opencensus.version@"
path = "./lib/opencensus-api-@opencensus.version@.jar"

[[platform.java21.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-contrib-http-util"
version = "@opencensus.version@"
path = "./lib/opencensus-contrib-http-util-@opencensus.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "@guava.version@"
path = "./lib/guava-@guava.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "@guava.failureaccess.version@"
path = "./lib/failureaccess-@guava.failureaccess.version@.jar"

[[platform.java21.dependency]]
groupId = "org.threeten"
artifactId = "threetenbp"
version = "@threetenbp.version@"
path = "./lib/threetenbp-@threetenbp.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "@j2objc.annotations.version@"
path = "./lib/j2objc-annotations-@j2objc.annotations.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "@jsr305.version@"
path = "./lib/jsr305-@jsr305.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "@err.prone.annotation.version@"
path = "./lib/error_prone_annotations-@err.prone.annotation.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.api-client"
artifactId = "google-api-client"
version = "@google.api.client.version@"
path = "./lib/google-api-client-@google.api.client.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.oauth-client"
artifactId = "google-oauth-client"
version = "@google.oauth.client.version@"
path = "./lib/google-oauth-client-@google.oauth.client.version@.jar"

[[platform.java21.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client-gson"
version = "@google.http.client.version@"
path = "./lib/google-http-client-gson-@google.http.client.version@.jar"

[[platform.java21.dependency]]
groupId = "io.perfmark"
artifactId = "perfmark-api"
version = "@perfmark.api.version@"
path = "./lib/perfmark-api-@perfmark.api.version@.jar"
