[package]
org = "ballerinax"
name = "gcloud.pubsub"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["pubsub", "google cloud", "messaging", "cloud", "gcp"]
repository = "https://github.com/ballerina-platform/module-ballerinax-gcloud.pubsub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "gcloud.pubsub-native"
version = "0.1.0"
path = "../native/build/libs/gcloud.pubsub-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "com.google.cloud"
artifactId = "google-cloud-pubsub"
version = "1.132.1"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "gax"
version = "2.52.0"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "gax-grpc"
version = "2.52.0"

[[platform.java21.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-credentials"
version = "1.24.1"

[[platform.java21.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-oauth2-http"
version = "1.24.1"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-netty-shaded"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-cloud-pubsub-v1"
version = "1.110.1"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "grpc-google-cloud-pubsub-v1"
version = "1.110.1"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "2.43.0"

[[platform.java21.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-iam-v1"
version = "1.37.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-api"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-core"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-auth"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-stub"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-protobuf"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-protobuf-lite"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.25.4"

[[platform.java21.dependency]]
groupId = "com.google.api"
artifactId = "api-common"
version = "2.35.0"

[[platform.java21.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client"
version = "1.44.2"

[[platform.java21.dependency]]
groupId = "com.google.code.gson"
artifactId = "gson"
version = "2.11.0"

[[platform.java21.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-api"
version = "0.31.1"

[[platform.java21.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-contrib-http-util"
version = "0.31.1"

[[platform.java21.dependency]]
groupId = "io.grpc"
artifactId = "grpc-context"
version = "1.66.0"

[[platform.java21.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "33.2.1-jre"

[[platform.java21.dependency]]
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "1.0.2"

[[platform.java21.dependency]]
groupId = "org.threeten"
artifactId = "threetenbp"
version = "1.6.9"

[[platform.java21.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "3.0.0"

[[platform.java21.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "3.0.2"

[[platform.java21.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "2.36.0"

[[platform.java21.dependency]]
groupId = "com.google.api-client"
artifactId = "google-api-client"
version = "2.7.0"

[[platform.java21.dependency]]
groupId = "com.google.oauth-client"
artifactId = "google-oauth-client"
version = "1.36.0"

[[platform.java21.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client-gson"
version = "1.44.2"

[[platform.java21.dependency]]
groupId = "io.perfmark"
artifactId = "perfmark-api"
version = "0.27.0"

[build-options]
observabilityIncluded=true
