name: Build Timestamped Master

on:
  push:
    branches:
      - main

jobs:
  call_workflow:
    name: Run Timestamped Build Master Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/build-timestamped-master-template.yml@main
    secrets: inherit
